### ISSUE TITLE
[PE-D][Tester A] Datetime issue

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#158] opened 2024-04-05 22:23 UTC
![image.png](https://raw.githubusercontent.com/YuZizhen/ped/main/files/af897bd4-61b3-4d31-8151-d7c97a462a20.png)
Start date later than the end date.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YuZizhen/ped#10

**Comment by wilsonwid** [comment] 2024-04-06 14:17
Duplicate of #121

**Closed by wilsonwid** 2024-04-06 14:17 UTC
