### ISSUE TITLE
[PE-D][Tester B] Add schedule command allows the user to input a end date that is before the start date

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-3/tp#148] opened 2024-04-05 22:15 UTC
**Maybe it would be good to parse the schedule command and produce an error if the end date is before the start date?**

<hr>

![image.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/2a5a283c-3eb0-462b-bc63-a3b0dcadaa60.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bgopi23/ped#16

**Comment by wilsonwid** [comment] 2024-04-06 14:11
Duplicate of #121

**Closed by wilsonwid** 2024-04-06 14:11 UTC
