### ISSUE TITLE
[PE-D][Tester B] Output of the help command is empty and does not match the one showed in the User Guide.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-3/tp#123] opened 2024-04-05 18:18 UTC
Maybe If a user does not have internet access, he will not be able to access the help menu offline as its blank and only provides a URL.
This could result in the user being unable to use the app as he does not know the commands.

**Maybe it would be good to have a short command summary in the help command itself that is available offline?**

<hr>

**_Actual:_**
![Screenshot 2024-04-05 at 4.36.08 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/95bd5f95-de37-4c17-8c5d-e6d5dcddb46d.png)

<hr>

**Expected (Shown in User Guide)**

![Screenshot 2024-04-05 at 4.37.20 PM.png](https://raw.githubusercontent.com/bgopi23/ped/main/files/c06b1b11-ac4a-4ba1-adce-bf2835ede1ed.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: bgopi23/ped#6

**Comment by wilsonwid** [comment] 2024-04-06 13:35
Duplicate of #110

**Closed by wilsonwid** 2024-04-06 13:35 UTC
